// <auto-generated />
using System;
using ComponyRegistrationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComponyRegistrationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818135855_InitialComponyRegistratio01")]
    partial class InitialComponyRegistratio01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponyRegistrationAPI.Models.Compony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Componies");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.ComponyRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponyId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponyId")
                        .IsUnique();

                    b.ToTable("ComponyRegistrations");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.ComponyRegistration", b =>
                {
                    b.HasOne("ComponyRegistrationAPI.Models.Compony", "Compony")
                        .WithOne("Registration")
                        .HasForeignKey("ComponyRegistrationAPI.Models.ComponyRegistration", "ComponyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compony");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.Compony", b =>
                {
                    b.Navigation("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
