// <auto-generated />
using System;
using ComponyRegistrationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComponyRegistrationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponyRegistrationAPI.Models.Compony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Componies");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.ComponyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ComponyBranches");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.ComponyRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponyId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponyId")
                        .IsUnique();

                    b.ToTable("ComponyRegistrations");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("services");
                });

            modelBuilder.Entity("ComponyService", b =>
                {
                    b.Property<int>("ComponiesId")
                        .HasColumnType("int");

                    b.Property<int>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("ComponiesId", "servicesId");

                    b.HasIndex("servicesId");

                    b.ToTable("ComponyService");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.ComponyBranch", b =>
                {
                    b.HasOne("ComponyRegistrationAPI.Models.Compony", "Compony")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compony");
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.ComponyRegistration", b =>
                {
                    b.HasOne("ComponyRegistrationAPI.Models.Compony", "Compony")
                        .WithOne("Registration")
                        .HasForeignKey("ComponyRegistrationAPI.Models.ComponyRegistration", "ComponyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compony");
                });

            modelBuilder.Entity("ComponyService", b =>
                {
                    b.HasOne("ComponyRegistrationAPI.Models.Compony", null)
                        .WithMany()
                        .HasForeignKey("ComponiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComponyRegistrationAPI.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("servicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComponyRegistrationAPI.Models.Compony", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
